### ISSUE TITLE
Delete all songs!!

### ISSUE THREAD

**Issue by zjankovsky** [DanielsWrath/SpotifyRandomizer#10]
Hey, it deletes all my song from playlist and nothing else! Be aware, make a copy of list at least!

**Comment by DanielHaitink** [comment]
Ill look into this! Should not happen, it should only delete the songs of the new random playlist.
@stavlocker maybe you can also look into this?

I am sorry

**Comment by zjankovsky** [comment]
The problem is on line [randomizer L199](https://github.com/DanielsWrath/SpotifyRandomizer/blob/4672d0f8f2479b3c4b1f38db38d0e13ce9737f18/randomizer.py#L199 ) because firstly it delete all the list, and then tries to get the songs!

So delete lines from 199 to 200 and put them after the line [203](https://github.com/DanielsWrath/SpotifyRandomizer/blob/4672d0f8f2479b3c4b1f38db38d0e13ce9737f18/randomizer.py#L203)

Now it works.
Better approach would be create new list with randomized song - you will not be deleting the original playlist.
Second possibility is to use [Reorder API ](https://developer.spotify.com/documentation/web-api/reference/playlists/reorder-playlists-tracks/) it doesnt delete anything - very safe.

**Comment by stavlocker** [comment]
This is due to a bug in the code where the program fetched the original playlist as the randomized playlist, which it tried to clear. I fixed this in my recent pull request (https://github.com/DanielsWrath/SpotifyRandomizer/pull/11) and added a case to never delete the original playlist even if a bug like this occurs ever again. @zjankovsky sorry for the inconvenience.

**Comment by zjankovsky** [comment]
Hi, thank you for fixing this. And thanks for sharing your tool.

One note: it seems to me that if you create new playlist it is always empty. It means, it is not neccessary to delete the songs in it - you can check its length, and when it is not empty throw an error. Clearing the list is not needed. Am I right?

**Comment by stavlocker** [comment]
@zjankovsky Partly. If I randomize a playlist for the first time then yes, the randomized playlist is created empty. But if I randomize it again (Without deleting the previously generated randomized playlist, because why would I?) I'd be adding songs on top of the previously randomized playlist. That's the case where I have to clear the randomized playlist first.

**Comment by zjankovsky** [comment]
Yes, that's definitly right. Thanks.
